### PR TITLE
Refactor classes to ES6 Class syntax

### PR DESCRIPTION
**Pull request by udielenberg**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Nice, thanks!

We should probably do this for all classes in the project, for consistency. Is this in your pieline, or should we find other volunteers?

**Comment by udielenberg** [comment]
I'll do it ✌️

**Comment by RubenVerborgh** [comment]
Thanks, I appreciate it!

**Comment by iddan** [comment]
All classes have been refactored

**Comment by iddan** [comment]
It can be merged even though @udielenberg hasn't updated the title yet

**Comment by iddan** [comment]
Breaking Changes:
 - Constructors can't be called without a `new` keyword as specified by ES6
 - DefaultGraph is a singleton object and not a class. This reduces the magic required for keeping one instance of the class.

**Comment by iddan** [comment]
I tried, but none of the ways I've tried worked.

**Comment by RubenVerborgh** [comment]
This does the trick:

```JavaScript
let instance;

class Singleton {
  constructor() {
    return instance || (instance = this);
  }
}

console.log(new Singleton() === new Singleton());
```

**Comment by iddan** [comment]
Cool, let me see if I can make it work

**Comment by iddan** [comment]
Seems like it breaks many of the tests. For some reason when taking this approach `this` becomes undefined. I think it's a correct move to make DefaultGraph an object and not a constructor which returns the same object. I'm unaware of any standard library that acts that way

**Comment by RubenVerborgh** [comment]
Thanks for trying, will look at it.

**Comment by RubenVerborgh** [comment]
Thanks a lot, and sorry for the delay.

**Pull request merged**
