### PR TITLE
+ instructions, scripts and testbed for browser products

### PR DESCRIPTION
**Pull request by ericprud**
I wanted to shorten the learniing curve for using N3.js in a browser.

Remaining issues:
1. I screwed around reading webpack docs for while then gave up to create a hack `N3-webpack.js` to emualte the behavior of `browserify -s N3`
2. The browser/simple.html page doesn't demonstrate reading from `ReadableStreams` as I never figured out how to. Other than that, it covers pretty much everything in the README.md.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Would it be okay if we pointed at this issue from the README, or if we put this in the wiki?

I'm asking because the code would need some editing to fit with the rest of the repo.

**Comment by ericprud** [comment]
I think I was supposed to have done something here. Since I didn't, what should we do now?

**Comment by RubenVerborgh** [comment]
We could wiki it, or I'd need to spend some time integrating it with the repo.

I don't mind doing the latter, it's just that my open source issue queue has become long lately, so it will take me a bit of time to get to it.

**Comment by RubenVerborgh** [comment]
Pausing this for now; feel free to revive at any point.

**Pull request closed without merging**
