### PR TITLE
Use rdf-test-suite for spec testing

### PR DESCRIPTION
**Pull request by rubensworks**
_Note: this is blocked by: https://github.com/w3c/rdf-tests/pull/53_

As described in #154, this uses [rdf-test-suite](https://www.npmjs.com/package/rdf-test-suite) for spec testing.

Advantages:
* Fix spec compliance not being tested anymore
* Removal of SWObjects as a (dev) dependency
* Uses the more up-to-date test suites from [RDF Test Curation Community Group](https://w3c.github.io/rdf-tests/).

Discovered 3 failing tests, so the Travis build fails because of this:
```
✖ nt-syntax-bad-string-04
  long single string literal (negative test)
  Error: Expected to throw an error when parsing.
  Query: <http://example/s> <http://example/p> '''abc''' .


  More info: http://w3c.github.io/rdf-tests/nquads/manifest.ttl#nt-syntax-bad-string-04


✖ nt-syntax-bad-string-05
  long double string literal (negative test)
  Error: Expected to throw an error when parsing.
  Query: <http://example/s> <http://example/p> """abc""" .


  More info: http://w3c.github.io/rdf-tests/nquads/manifest.ttl#nt-syntax-bad-string-05

✖ sole_blankNodePropertyList
  sole blankNodePropertyList [ <p> <o> ] .
  Error: Unexpected } on line 3.
  More info: http://w3c.github.io/rdf-tests/trig/manifest.ttl#sole_blankNodePropertyList
```

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks, will look at failing tests!

**Comment by RubenVerborgh** [comment]
@rubensworks I'm also seeing blank node failures: https://travis-ci.org/rdfjs/N3.js/jobs/463382092#L2778

**Comment by rubensworks** [comment]
Yeah, those tests are wrong. Fixed them in https://github.com/w3c/rdf-tests/pull/53.

**Comment by RubenVerborgh** [comment]
Thanks! Actually, only 2 are failing now: turtle-subm-01 and turtle-subm-27. The first one seems a false negative, the second one still seems base IRI-related. What do you make of it?

**Comment by rubensworks** [comment]
Ah, you'll have to clear the Travis cache first, because [I enabled caching for all fetched resources](https://github.com/rdfjs/N3.js/blob/2a9b62db18b3bf81536dda6581b01a0640bcdfd4/.travis.yml#L24). (I can disable caching again if you prefer that)

And regarding the test output, it looks like bash is short-circuiting the first failure: https://github.com/rdfjs/N3.js/blob/2a9b62db18b3bf81536dda6581b01a0640bcdfd4/package.json#L38
So I'll have to come up with a better system for that...

**Comment by rubensworks** [comment]
Changed things around a bit.

All spec tests will now run, even if the previous ones failed.
Also, Travis will fail once at least one of the spec tests fails.

The Travis cache has to be cleared for this build in order to get the updated tests (https://github.com/w3c/rdf-tests/pull/53). (You'll have to do this, as I don't have permissions for this)

**Comment by RubenVerborgh** [comment]
@rubensworks Thanks so much!

**Pull request merged**
