### PR TITLE
fix: Correctly handle custom data factories by binding functions

### LINKED ISSUE #466: Custom data factories are incorrectly handled
When injecting a custom factory into the `StreamParser` (possibly other places as well), the factory methods are being used as standalone functions instead of methods on the factory object.
This makes it so that custom factories (such as `rdf-data-factory`) that rely on an internal `this` state will start failing, which causes issues such as https://github.com/rubensworks/rdf-dereference.js/issues/55.

I suspect the solution may be as simple as just `bind`-ing the extracted factory functions to `factory` [here](https://github.com/rdfjs/N3.js/blob/main/src/N3Parser.js#L1086-L1092).

### PR DESCRIPTION
**Pull request by smessie**
Closes #466.
Tested this and this seems to resolve https://github.com/rubensworks/rdf-dereference.js/issues/55

## Summary by CodeRabbit

- **New Features**
	- Enhanced the parser's interaction with the data factory for improved functionality.
	- Improved method bindings to ensure correct context during execution.
	- Added new test cases to validate the parser's handling of RDF-star syntax and complex scenarios, including edge cases.

- **Bug Fixes**
	- Resolved issues related to method scoping in the parser, ensuring expected behavior during data processing.

### CODE REVIEW

**Comment by jeswr** [comment]
That's @smessie ! Could you add some regression tests?

**Comment by smessie** [comment]
Added a small test @jeswr

**Review by RubenVerborgh — CHANGES_REQUESTED** [review]
Instead of binding, can we call them on the `factory` object?
These functions are called hundreds of thousands of times per second; the difference might matter in some engines.

**Review by jeswr — APPROVED** [review]

**Comment by jeswr** [comment]
I did performance testing with the latest commit and there is no statistically significant difference compared to the main branch.

**Pull request merged**
